name: Test build — Windows
run-name: ${{ github.actor }} is building for Windows.

on:
  pull_request:
    branches: [ main ]
    
jobs:
  test-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install python dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build and deploy on Windows
        run: npm run build:win
