name: Test build — Mac Intel
run-name: ${{ github.actor }} is building for MacOS.

on:
  pull_request:
    branches: [ main ]

jobs:
  test-on-mac:
    runs-on: macos-13  
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install python dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build and deploy on Mac
        run: npm run build:mac -- --publish=never --x64